#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target "UniversalProduct" do
project 'UniversalProduct.xcodeproj'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'AFNetworking', '~> 3.0'
pod 'LGAlertView', '~> 2.0.0'
pod 'MJRefresh'
end
